DECLARE 
	N NUMBER;
	I NUMBER;
	FLAG NUMBER:=0;
BEGIN 
	N:=&N_INPUT;
	FOR I IN 2..N/2 LOOP
		IF N MOD I=0 THEN 
			FLAG:=1;
			EXIT;
		END IF;
	END LOOP;
	IF FLAG=0 THEN 
		DBMS_OUTPUT.PUT_LINE(N||' IS PRIME.' );
	ELSE 
		DBMS_OUTPUT.PUT_LINE(N||' IS NOT PRIME.' );
	END IF;
END;
/