CREATE TABLE ITEM_8(ITEM_NO NUMBER(1), ITEM_NAME VARCHAR2(10), PRICE NUMBER(6));
INSERT INTO ITEM_8 VALUES(1, 'PC', 30000);
INSERT INTO ITEM_8 VALUES(2, 'MOBILE', 20000);
INSERT INTO ITEM_8 VALUES(3, 'WATCH', 5000);
INSERT INTO ITEM_8 VALUES(4, 'EARPODS', 10000);
INSERT INTO ITEM_8 VALUES(5, 'ALEXA', 20000);
UPDATE ITEM_8 SET PRICE=15000 WHERE ITEM_NO=4;
DELETE FROM ITEM_8 WHERE ITEM_NAME='ALEXA';
DECLARE 
	ITEM_NO NUMBER;
	ITEM_NAME VARCHAR2(10);
	PRICE NUMBER;
BEGIN
	SELECT ITEM_NO, ITEM_NAME, PRICE
	INTO ITEM_NO, ITEM_NAME,PRICE
	FROM ITEM_8
	WHERE ITEM_NAME='MOBILE';
	DBMS_OUTPUT.PUT_LINE('ITEM_NO:' ||ITEM_NO);
	DBMS_OUTPUT.PUT_LINE('ITEM_NAME:' ||ITEM_NAME);
	DBMS_OUTPUT.PUT_LINE('PRICE:' ||PRICE);
END;
/